AllCops:
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - 'lib/omniauth-tiktok-loginkit.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb' # good test write long